default_platform(:ios)

platform :ios do
  desc "Build release IPA"
  lane :build do
    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "Stuga.ipa"
    )
  end

  desc "Upload dSYMs to Firebase Crashlytics"
  lane :upload_dsyms do
    download_dsyms(
      app_identifier: "se.twinbolt.stuga"
    )
    upload_symbols_to_crashlytics(
      gsp_path: "../App/GoogleService-Info.plist"
    )
    clean_build_artifacts
  end

  desc "Upload to TestFlight"
  lane :beta do
    build
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy to App Store"
  lane :release do
    build
    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: false,
      force: true
    )
  end

  desc "Upload metadata only (no build)"
  lane :metadata do
    upload_to_app_store(
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true
    )
  end
end
